pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

includeBuild("../SableRagdollLib") {
    dependencySubstitution {
        substitute(module("com.gly091020:sableragdolllib"))
                .using(project(":"))
    }
}

includeBuild("../Love-And-Loathe") {
    dependencySubstitution {
        substitute(module("com.github.tartaricacid:callresponse"))
                .using(project(":"))
    }
}
